# Generated by Django 3.2.25 on 2024-12-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20241218_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isVerified',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
